plotEpicurve <- function(data, title = "Epicurve") {
  #
  # Descrition
  # Plot epidemic curve of delayed data
  #
  # Arguments
  # data    Dataframe generated by dataSetup
  # title   Title of the plot
  #
  # Value
  # ggplot object
  
  # Prepare data for epicurve plot
  tmp <- data %>%
    group_by(Date, Reported) %>%
    summarize(Cases = sum(Cases))
  
  # Make the plot
  plot <- ggplot(
    data = tmp,
    mapping = aes(x = Date, y = Cases, fill = Reported)) +
    geom_col(
      width = 1,
      position = position_stack(reverse = TRUE)) +
    scale_fill_manual(
      values = c(blue, oran, grey),
      name = "") +
    scale_x_date(
      date_breaks = "1 month",
      date_labels = "%b %d",
      expand = c(0, 0)) +
    scale_y_continuous(
      limits = c(0, with(data, max(tapply(Cases, Date, sum)) + 1)),
      expand = c(0, 0)) +
    labs(
      x = "Time of symptoms onset",
      y = "Number of symptomatic cases",
      title = paste(title, "-", format(with(subset(data, Reported == "Reported"), max(Date)), format = "%b %d, %Y"))) +
    theme_bw() +
    theme(
      plot.margin = margin(t = 0.1, r = 0.5, b = 0.1, l = 0.1, unit = "cm"),
      plot.title = element_text(hjust = 0.5),
      legend.position = "top")
  
  # Return output
  return(plot)
  
}
